spring:
  datasource:
    url: jdbc:mysql://localhost:3306/projetomusica #3306 eh a porta padrao do MySQL
    username: root
    password: Linux2021.
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true #Define se o SQL gerado pelo Hibernate deve ser exibido no console. Neste caso, está configurado para exibir o SQL.
    hibernate:
      ddl-auto: update
      #significa que o Hibernate irá atualizar automaticamente o esquema do banco de dados conforme as entidades são alteradas.

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}